TEC-4882 - Add in loading of post types and central menu for all post…
roadwarriorwp/wpconferenceschedule pull request #10
Opened 2023-08-21 15:40 UTC by jesseeproductions

… types.

2023-08-22 13:02 UTC, bordoni requested changes
Small changes but not required honestly.

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Admin/Menu.php
> +		);
Save the return of `add_menu_page` to a variable, it can be used later for hooks.
https://developer.wordpress.org/reference/functions/add_menu_page/#return

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Admin/Menu.php
> +			'Add New Sponsor',
Same for these, add the returning strings to an array of `$submenu_hook_prefix` or something like that.

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Plugin.php
> +		flush_rewrite_rules();
Was this there before? This tends to be too early to flush, dynamic rules might not be included correctly.

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Post_Types/Provider.php
> +		add_action( 'enter_title_here', [ $this, 'change_sponsors_title_text' ], 10, 2 );
These are filters right?

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Post_Types/Sessions.php
> +		] );
Allow filtering here, it should help integration later, filter the args array. If you move to a separate method makes it easier to read.

Also save the return locally, it allows for usage later without any costs:
https://developer.wordpress.org/reference/functions/register_post_type/#return

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Post_Types/Sessions.php
> +	function cpt_at_glance() {
```suggestion
	public function cpt_at_glance() {
```

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Post_Types/Speakers.php
> +			'has_archive'        => false,
Same as the other CPT. Save the object return and allow filtering.

2023-08-22 13:02 UTC, bordoni commented on src/Conference/Post_Types/Sponsors.php
> +		] );
Same as the other CPT. Save the object return and allow filtering.

2023-08-22 14:14 UTC, jesseeproductions commented on src/Conference/Plugin.php
> +		flush_rewrite_rules();
It was part of their coding. I commented it out. This and the deactivation methods need to be revisited later on.

2023-08-30 14:55 UTC, bordoni approved these changes

2023-08-30 16:03 UTC, merged