Feature/tec 4882 settings
roadwarriorwp/wpconferenceschedule pull request #12
Opened 2023-08-30 14:42 UTC by jesseeproductions

- Adds all settings to their own class
- Add settings link under the Conference Schedule admin menu. 
- Keeps html and display from current plugin. 

Artifact:
-Settings Admin Link and Page - https://cloudup.com/c1gi2B9PL9p

_Ref:_ [TEC-4882](https://theeventscalendar.atlassian.net/browse/TEC-4882)

2023-08-30 21:00 UTC, bordoni requested changes

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +			</option>
Translations.

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +			</option>
Translations.

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +		<p class="description">The location to redirect sponsor links to on the session single page.</p>
Translations.

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +			} ?>>Redirect to Sponsor Site
```suggestion
			<option value="sponsor_site" <?php selected( $sponsor_url == 'sponsor_site' ); ?>>Redirect to Sponsor Site
```

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +		return '';
`in_array`?

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +				submit_button( 'Save Settings' );
Translations.

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +		<p class="description">The URL of the page that your speakers are embedded on.</p>
Translation

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +		<p class="description">The URL of the page that your conference schedule is embedded on.</p>
Translation

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Settings.php
> +			<?php esc_html_e( '', 'wpcs' ); ?>
Why leave it empty?

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Columns.php
> +		if ( ! in_array( $session_type, ['session', 'custom', 'mainstage'], true ) ) {
```suggestion
		if ( ! in_array( $session_type, [ 'session', 'custom', 'mainstage' ], true ) ) {
```

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Columns.php
> +		$session_type = get_post_meta( $post->ID, '_wpcs_session_type', true );
Should this meta be a static var?

2023-08-30 21:00 UTC, bordoni commented on src/Conference/Admin/Columns.php
> +		}
Invert logic and bail to reduce cognitive load.

2023-09-01 11:17 UTC, jesseeproductions commented on src/Conference/Admin/Columns.php
> +		$session_type = get_post_meta( $post->ID, '_wpcs_session_type', true );
It changes for every session. So I do not think it would be static.

2023-09-01 11:23 UTC, jesseeproductions commented on src/Conference/Admin/Settings.php
> +			<?php esc_html_e( '', 'wpcs' ); ?>
Not sure why, but it hides the rest of the settings. I removed the empty translation text.

2023-09-06 13:26 UTC, bordoni approved these changes

2023-09-06 16:45 UTC, merged